/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Answer model module.
 * @module model/Answer
 * @version 1.0.11
 */
export class Answer {
  /**
   * Constructs a new <code>Answer</code>.
   * @alias module:model/Answer
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Answer</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Answer} obj Optional instance to populate.
   * @return {module:model/Answer} The populated <code>Answer</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Answer();
      if (data.hasOwnProperty('answerId'))
        obj.answerId = ApiClient.convertToType(data['answerId'], 'String');
      if (data.hasOwnProperty('Body'))
        obj.body = ApiClient.convertToType(data['Body'], 'String');
      if (data.hasOwnProperty('Votes'))
        obj.votes = ApiClient.convertToType(data['Votes'], 'Number');
      if (data.hasOwnProperty('questionId'))
        obj.questionId = ApiClient.convertToType(data['questionId'], 'String');
      if (data.hasOwnProperty('CreatedBy'))
        obj.createdBy = ApiClient.convertToType(data['CreatedBy'], 'String');
      if (data.hasOwnProperty('CreatedAt'))
        obj.createdAt = ApiClient.convertToType(data['CreatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} answerId
 */
Answer.prototype.answerId = undefined;

/**
 * @member {String} body
 */
Answer.prototype.body = undefined;

/**
 * @member {Number} votes
 */
Answer.prototype.votes = undefined;

/**
 * @member {String} questionId
 */
Answer.prototype.questionId = undefined;

/**
 * @member {String} createdBy
 */
Answer.prototype.createdBy = undefined;

/**
 * @member {String} createdAt
 */
Answer.prototype.createdAt = undefined;

