/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The Search model module.
 * @module model/Search
 * @version 1.0.11
 */
export class Search {
  /**
   * Constructs a new <code>Search</code>.
   * @alias module:model/Search
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>Search</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Search} obj Optional instance to populate.
   * @return {module:model/Search} The populated <code>Search</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Search();
      if (data.hasOwnProperty('searchTags'))
        obj.searchTags = ApiClient.convertToType(data['searchTags'], ['String']);
      if (data.hasOwnProperty('searchSort'))
        obj.searchSort = ApiClient.convertToType(data['searchSort'], 'String');
      if (data.hasOwnProperty('searchResults'))
        obj.searchResults = ApiClient.convertToType(data['searchResults'], ['String']);
      if (data.hasOwnProperty('NumberOfSearchResults'))
        obj.numberOfSearchResults = ApiClient.convertToType(data['NumberOfSearchResults'], 'Number');
    }
    return obj;
  }
}

/**
 * @member {Array.<String>} searchTags
 */
Search.prototype.searchTags = undefined;

/**
 * @member {String} searchSort
 */
Search.prototype.searchSort = undefined;

/**
 * @member {Array.<String>} searchResults
 */
Search.prototype.searchResults = undefined;

/**
 * @member {Number} numberOfSearchResults
 */
Search.prototype.numberOfSearchResults = undefined;

