/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from '../ApiClient';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.11
 */
export class User {
  /**
   * Constructs a new <code>User</code>.
   * @alias module:model/User
   * @class
   */
  constructor() {
  }

  /**
   * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/User} obj Optional instance to populate.
   * @return {module:model/User} The populated <code>User</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new User();
      if (data.hasOwnProperty('userId'))
        obj.userId = ApiClient.convertToType(data['userId'], 'String');
      if (data.hasOwnProperty('username'))
        obj.username = ApiClient.convertToType(data['username'], 'String');
      if (data.hasOwnProperty('password'))
        obj.password = ApiClient.convertToType(data['password'], 'String');
      if (data.hasOwnProperty('rating'))
        obj.rating = ApiClient.convertToType(data['rating'], 'Number');
      if (data.hasOwnProperty('QuestionsAsked'))
        obj.questionsAsked = ApiClient.convertToType(data['QuestionsAsked'], ['String']);
      if (data.hasOwnProperty('NumberOfQuestionsAsked'))
        obj.numberOfQuestionsAsked = ApiClient.convertToType(data['NumberOfQuestionsAsked'], 'Number');
      if (data.hasOwnProperty('AnswersGiven'))
        obj.answersGiven = ApiClient.convertToType(data['AnswersGiven'], ['String']);
      if (data.hasOwnProperty('NumberOfAnswersGiven'))
        obj.numberOfAnswersGiven = ApiClient.convertToType(data['NumberOfAnswersGiven'], 'Number');
      if (data.hasOwnProperty('ProfilePicture'))
        obj.profilePicture = ApiClient.convertToType(data['ProfilePicture'], 'String');
      if (data.hasOwnProperty('email'))
        obj.email = ApiClient.convertToType(data['email'], 'String');
    }
    return obj;
  }
}

/**
 * @member {String} userId
 */
User.prototype.userId = undefined;

/**
 * @member {String} username
 */
User.prototype.username = undefined;

/**
 * @member {String} password
 */
User.prototype.password = undefined;

/**
 * @member {Number} rating
 */
User.prototype.rating = undefined;

/**
 * @member {Array.<String>} questionsAsked
 */
User.prototype.questionsAsked = undefined;

/**
 * @member {Number} numberOfQuestionsAsked
 */
User.prototype.numberOfQuestionsAsked = undefined;

/**
 * @member {Array.<String>} answersGiven
 */
User.prototype.answersGiven = undefined;

/**
 * @member {Number} numberOfAnswersGiven
 */
User.prototype.numberOfAnswersGiven = undefined;

/**
 * @member {String} profilePicture
 */
User.prototype.profilePicture = undefined;

/**
 * @member {String} email
 */
User.prototype.email = undefined;

