/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QueriKornerOpenApi30);
  }
}(this, function(expect, QueriKornerOpenApi30) {
  'use strict';

  var instance;

  describe('(package)', function() {
    describe('Search', function() {
      beforeEach(function() {
        instance = new QueriKornerOpenApi30.Search();
      });

      it('should create an instance of Search', function() {
        // TODO: update the code to test Search
        expect(instance).to.be.a(QueriKornerOpenApi30.Search);
      });

      it('should have the property searchTags (base name: "searchTags")', function() {
        // TODO: update the code to test the property searchTags
        expect(instance).to.have.property('searchTags');
        // expect(instance.searchTags).to.be(expectedValueLiteral);
      });

      it('should have the property searchSort (base name: "searchSort")', function() {
        // TODO: update the code to test the property searchSort
        expect(instance).to.have.property('searchSort');
        // expect(instance.searchSort).to.be(expectedValueLiteral);
      });

      it('should have the property searchResults (base name: "searchResults")', function() {
        // TODO: update the code to test the property searchResults
        expect(instance).to.have.property('searchResults');
        // expect(instance.searchResults).to.be(expectedValueLiteral);
      });

      it('should have the property numberOfSearchResults (base name: "NumberOfSearchResults")', function() {
        // TODO: update the code to test the property numberOfSearchResults
        expect(instance).to.have.property('numberOfSearchResults');
        // expect(instance.numberOfSearchResults).to.be(expectedValueLiteral);
      });

    });
  });

}));
