# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Search(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, search_tags: List[str]=None, search_sort: str=None, search_results: List[str]=None, number_of_search_results: int=None):  # noqa: E501
        """Search - a model defined in Swagger

        :param search_tags: The search_tags of this Search.  # noqa: E501
        :type search_tags: List[str]
        :param search_sort: The search_sort of this Search.  # noqa: E501
        :type search_sort: str
        :param search_results: The search_results of this Search.  # noqa: E501
        :type search_results: List[str]
        :param number_of_search_results: The number_of_search_results of this Search.  # noqa: E501
        :type number_of_search_results: int
        """
        self.swagger_types = {
            'search_tags': List[str],
            'search_sort': str,
            'search_results': List[str],
            'number_of_search_results': int
        }

        self.attribute_map = {
            'search_tags': 'searchTags',
            'search_sort': 'searchSort',
            'search_results': 'searchResults',
            'number_of_search_results': 'NumberOfSearchResults'
        }
        self._search_tags = search_tags
        self._search_sort = search_sort
        self._search_results = search_results
        self._number_of_search_results = number_of_search_results

    @classmethod
    def from_dict(cls, dikt) -> 'Search':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Search of this Search.  # noqa: E501
        :rtype: Search
        """
        return util.deserialize_model(dikt, cls)

    @property
    def search_tags(self) -> List[str]:
        """Gets the search_tags of this Search.


        :return: The search_tags of this Search.
        :rtype: List[str]
        """
        return self._search_tags

    @search_tags.setter
    def search_tags(self, search_tags: List[str]):
        """Sets the search_tags of this Search.


        :param search_tags: The search_tags of this Search.
        :type search_tags: List[str]
        """

        self._search_tags = search_tags

    @property
    def search_sort(self) -> str:
        """Gets the search_sort of this Search.


        :return: The search_sort of this Search.
        :rtype: str
        """
        return self._search_sort

    @search_sort.setter
    def search_sort(self, search_sort: str):
        """Sets the search_sort of this Search.


        :param search_sort: The search_sort of this Search.
        :type search_sort: str
        """

        self._search_sort = search_sort

    @property
    def search_results(self) -> List[str]:
        """Gets the search_results of this Search.


        :return: The search_results of this Search.
        :rtype: List[str]
        """
        return self._search_results

    @search_results.setter
    def search_results(self, search_results: List[str]):
        """Sets the search_results of this Search.


        :param search_results: The search_results of this Search.
        :type search_results: List[str]
        """

        self._search_results = search_results

    @property
    def number_of_search_results(self) -> int:
        """Gets the number_of_search_results of this Search.


        :return: The number_of_search_results of this Search.
        :rtype: int
        """
        return self._number_of_search_results

    @number_of_search_results.setter
    def number_of_search_results(self, number_of_search_results: int):
        """Sets the number_of_search_results of this Search.


        :param number_of_search_results: The number_of_search_results of this Search.
        :type number_of_search_results: int
        """

        self._number_of_search_results = number_of_search_results
