/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {Tag} from '../model/Tag';

/**
* Tags service.
* @module api/TagsApi
* @version 1.0.11
*/
export class TagsApi {

    /**
    * Constructs a new TagsApi. 
    * @alias module:api/TagsApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the createTag operation.
     * @callback moduleapi/TagsApi~createTagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tag{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create tag
     * Create tag
     * @param {module:model/Tag} body Tag to be added to the database
     * @param {module:api/TagsApi~createTagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    createTag(body, callback) {
      
      let postBody = body;
      // verify the required parameter 'body' is set
      if (body === undefined || body === null) {
        throw new Error("Missing the required parameter 'body' when calling createTag");
      }

      let pathParams = {
        
      };
      let queryParams = {
        
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ask_auth'];
      let contentTypes = ['application/json', 'application/xml'];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Tag;

      return this.apiClient.callApi(
        '/tags', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the deleteTag operation.
     * @callback moduleapi/TagsApi~deleteTagCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tag{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an tag
     * Delete an tag
     * @param {Object} opts Optional parameters
     * @param {String} opts.tagId Tag id
     * @param {module:api/TagsApi~deleteTagCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    deleteTag(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'tagId': opts['tagId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ask_auth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Tag;

      return this.apiClient.callApi(
        '/tags/{tagId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
    /**
     * Callback function to receive the result of the getTagData operation.
     * @callback moduleapi/TagsApi~getTagDataCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Tag{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get tag data
     * Get tag data
     * @param {Object} opts Optional parameters
     * @param {String} opts.tagId Tag id
     * @param {module:api/TagsApi~getTagDataCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    getTagData(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'tagId': opts['tagId']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['ask_auth'];
      let contentTypes = [];
      let accepts = ['application/json', 'application/xml'];
      let returnType = Tag;

      return this.apiClient.callApi(
        '/tags/{tagId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}