/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QueriKornerOpenApi30);
  }
}(this, function(expect, QueriKornerOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QueriKornerOpenApi30.AnswerApi();
  });

  describe('(package)', function() {
    describe('AnswerApi', function() {
      describe('changeAnswer', function() {
        it('should call changeAnswer successfully', function(done) {
          // TODO: uncomment, update parameter values for changeAnswer call and complete the assertions
          /*
          var opts = {};

          instance.changeAnswer(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Answer);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteAnswer', function() {
        it('should call deleteAnswer successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteAnswer call and complete the assertions
          /*
          var opts = {};

          instance.deleteAnswer(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Answer);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getDatafromAnswer', function() {
        it('should call getDatafromAnswer successfully', function(done) {
          // TODO: uncomment, update parameter values for getDatafromAnswer call and complete the assertions
          /*
          var opts = {};

          instance.getDatafromAnswer(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Answer);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('postAnswer', function() {
        it('should call postAnswer successfully', function(done) {
          // TODO: uncomment, update parameter values for postAnswer call and complete the assertions
          /*
          var opts = {};

          instance.postAnswer(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Answer);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('upvoteAnswer', function() {
        it('should call upvoteAnswer successfully', function(done) {
          // TODO: uncomment, update parameter values for upvoteAnswer call and complete the assertions
          /*
          var opts = {};

          instance.upvoteAnswer(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Answer);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
