/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QueriKornerOpenApi30);
  }
}(this, function(expect, QueriKornerOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QueriKornerOpenApi30.QuestionApi();
  });

  describe('(package)', function() {
    describe('QuestionApi', function() {
      describe('askQuery', function() {
        it('should call askQuery successfully', function(done) {
          // TODO: uncomment, update parameter values for askQuery call and complete the assertions
          /*

          instance.askQuery(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Question);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('changeQuestion', function() {
        it('should call changeQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for changeQuestion call and complete the assertions
          /*
          var opts = {};

          instance.changeQuestion(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Question);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteQuery', function() {
        it('should call deleteQuery successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteQuery call and complete the assertions
          /*
          var opts = {};

          instance.deleteQuery(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Question);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getData', function() {
        it('should call getData successfully', function(done) {
          // TODO: uncomment, update parameter values for getData call and complete the assertions
          /*
          var opts = {};

          instance.getData(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Question);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('upvoteQuestion', function() {
        it('should call upvoteQuestion successfully', function(done) {
          // TODO: uncomment, update parameter values for upvoteQuestion call and complete the assertions
          /*
          var opts = {};

          instance.upvoteQuestion(body, opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Question);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
