/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.QueriKornerOpenApi30);
  }
}(this, function(expect, QueriKornerOpenApi30) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new QueriKornerOpenApi30.TagsApi();
  });

  describe('(package)', function() {
    describe('TagsApi', function() {
      describe('createTag', function() {
        it('should call createTag successfully', function(done) {
          // TODO: uncomment, update parameter values for createTag call and complete the assertions
          /*

          instance.createTag(body, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Tag);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('deleteTag', function() {
        it('should call deleteTag successfully', function(done) {
          // TODO: uncomment, update parameter values for deleteTag call and complete the assertions
          /*
          var opts = {};

          instance.deleteTag(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Tag);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('getTagData', function() {
        it('should call getTagData successfully', function(done) {
          // TODO: uncomment, update parameter values for getTagData call and complete the assertions
          /*
          var opts = {};

          instance.getTagData(opts, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }
            // TODO: update response assertions
            expect(data).to.be.a(QueriKornerOpenApi30.Tag);

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
