/*
 * queriKorner - OpenAPI 3.0
 * This is the API documentation of the queriKorner server application. It is based on the OpenAPI 3.0 specification.
 *
 * OpenAPI spec version: 1.0.11
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.41
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from './ApiClient';
import {Answer} from './model/Answer';
import {Question} from './model/Question';
import {Search} from './model/Search';
import {Tag} from './model/Tag';
import {User} from './model/User';
import {AnswerApi} from './api/AnswerApi';
import {QuestionApi} from './api/QuestionApi';
import {SearchApi} from './api/SearchApi';
import {TagsApi} from './api/TagsApi';
import {UserApi} from './api/UserApi';

/**
* This_is_the_API_documentation_of_the_queriKorner_server_application__It_is_based_on_the_OpenAPI_3_0_specification_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var QueriKornerOpenApi30 = require('index'); // See note below*.
* var xxxSvc = new QueriKornerOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new QueriKornerOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new QueriKornerOpenApi30.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new QueriKornerOpenApi30.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.11
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Answer model constructor.
     * @property {module:model/Answer}
     */
    Answer,

    /**
     * The Question model constructor.
     * @property {module:model/Question}
     */
    Question,

    /**
     * The Search model constructor.
     * @property {module:model/Search}
     */
    Search,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The AnswerApi service constructor.
    * @property {module:api/AnswerApi}
    */
    AnswerApi,

    /**
    * The QuestionApi service constructor.
    * @property {module:api/QuestionApi}
    */
    QuestionApi,

    /**
    * The SearchApi service constructor.
    * @property {module:api/SearchApi}
    */
    SearchApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The UserApi service constructor.
    * @property {module:api/UserApi}
    */
    UserApi
};
